const withTW = require( '@bsf/force-ui/withTW' );

module.exports = withTW( {
	content: [ './src/**/*.{js,jsx}' ],
	theme: {
		extend: {
			colors: {
				// brand
				'brand-background-50': '#FFF3EE',
				'brand-background-hover-100': '#FFE9E0',
				'brand-200': '#FED7C7',
				'brand-border-300': '#FCBFA5',
				'brand-400': '#F8A581',
				'brand-500': '#F18E63',
				'brand-primary-600': '#DC4809',
				'brand-hover-700': '#C83B00',
				'brand-800': '#D54407',
				'brand-900': '#81472E',
				'brand-text-950': '#4B291B',
				// background
				'background-primary': '#FFFFFF',
				'background-secondary': '#F9FAFB',
				'background-inverse': '#1F2937',
				'background-brand': '#D54407',
				'background-important': '#DC2626',
				'background-tertiary': '#F3F4F6',
				// field
				'field-primary-background': '#F9FAFB',
				'field-secondary-background': '#FFFFFF',
				'field-primary-hover': '#F3F4F6',
				'field-secondary-hover': '#F9FAFB',
				'field-dropzone-background': '#FFFFFF',
				'field-border': '#E5E7EB',
				'field-dropzone-background-hover': '#F9FAFB',
				'field-dropzone-color': '#4F46E5',
				'field-label': '#111827',
				'field-input': '#4B5563',
				'field-helper': '#9CA3AF',
				'field-background-disabled': '#F9FAFB',
				'field-color-disabled': '#D1D5DB',
				'field-placeholder': '#9CA3AF',
				'field-border-disabled': '#F3F4F6',
				'field-color-error': '#DC2626',
				'field-border-error': '#FECACA',
				'field-background-error': '#FEF2F2',
				'field-required': '#DC2626',
				// border
				'border-interactive': '#D54407',
				'border-subtle': '#E5E7EB',
				'border-strong': '#6B7280',
				'border-inverse': '#374151',
				'border-disabled': '#E5E7EB',
				'border-muted': '#E5E7EB',
				'border-error': '#FECACA',
				'border-transparent-subtle': '#37415114',
				'border-white': '#FFFFFF',
				// text
				'text-primary': '#111827',
				'text-secondary': '#4B5563',
				'text-tertiary': '#9CA3AF',
				'text-on-color': '#FFFFFF',
				'text-error': '#DC2626',
				'text-error-inverse': '#F87171',
				'text-inverse': '#FFFFFF',
				'text-disabled': '#D1D5DB',
				'text-on-button-disabled': '#6B7280',
				// link
				'link-primary': '#D54407',
				'link-primary-hover': '#C83B00',
				'link-inverse': '#F8A581',
				'link-visited': '#DC4809',
				'link-visited-inverse': '#22D3EE',
				'link-inverse-hover': '#FCBFA5',
				// icon
				'icon-primary': '#111827',
				'icon-secondary': '#6B7280',
				'icon-on-color': '#FFFFFF',
				'icon-inverse': '#FFFFFF',
				'icon-interactive': '#D54407',
				'icon-on-color-disabled': '#9CA3AF',
				'icon-disabled': '#D1D5DB',
				// support
				'support-error': '#DC2626',
				'support-success': '#16A34A',
				'support-warning': '#EAB308',
				'support-info': '#0284C7',
				'support-error-inverse': '#F87171',
				'support-success-inverse': '#4ADE80',
				'support-warning-inverse': '#FDE047',
				'support-info-inverse': '#38BDF8',
				// button
				'button-primary': '#D54407',
				'button-primary-hover': '#C83B00',
				'button-secondary': '#1F2937',
				'button-secondary-hover': '#374151',
				'button-tertiary': '#FFFFFF',
				'button-tertiary-hover': '#F9FAFB',
				'button-danger': '#DC2626',
				'button-danger-secondary': '#DC2626',
				'button-danger-hover': '#B91C1C',
				'button-disabled': '#F3F4F6',
				'button-tertiary-border': '#E5E7EB',
				'button-tertiary-color': '#111827',
				// focus
				focus: '#DC4809',
				'focus-inset': '#FFFFFF',
				'focus-inverse': '#F8A581',
				'focus-inverse-inset': '#1F2937',
				'focus-error': '#DC2626',
				'focus-border': '#FCBFA5',
				'focus-error-border': '#FECACA',
				// misc
				'misc-highlight': '#BFDBFE',
				'misc-overlay': '#111827BF',
				'misc-skeleton-background': '#F3F4F6',
				'misc-skeleton-element': '#BDC1C7',
				'misc-popup-button-hover': '#1118270D',
				'misc-tab-item-hover': '#F3F4F6',
				'misc-dropdown-hover': '#F3F4F6',
				'misc-loader-base': '#1118270D',
				'misc-loader-color': '#DC4809',
				'misc-progress-background': '#E5E7EB',
				// badge
				'badge-background-gray': '#F9FAFB',
				'badge-color-gray': '#1F2937',
				'badge-hover-gray': '#F3F4F6',
				'badge-border-gray': '#E5E7EB',
				'badge-background-red': '#FEF2F2',
				'badge-color-red': '#B91C1C',
				'badge-hover-red': '#FEE2E2',
				'badge-border-red': '#FECACA',
				'badge-background-yellow': '#FEFCE8',
				'badge-color-yellow': '#A16207',
				'badge-hover-yellow': '#FEF9C3',
				'badge-border-yellow': '#FEF08A',
				'badge-hover-green': '#DCFCE7',
				'badge-border-green': '#BBF7D0',
				'badge-background-green': '#F0FDF4',
				'badge-color-green': '#15803D',
				'badge-background-sky': '#F0F9FF',
				'badge-color-sky': '#0369A1',
				'badge-hover-sky': '#E0F2FE',
				'badge-border-sky': '#BAE6FD',
				'badge-background-disabled': '#F3F4F6',
				'badge-color-disabled': '#D1D5DB',
				'badge-hover-disabled': '#F3F4F6',
				'badge-border-disabled': '#E5E7EB',
				'badge-background-important': '#DC2626',
				// alert
				'alert-background-neutral': '#FFFFFF',
				'alert-border-neutral': '#E5E7EB',
				'alert-background-danger': '#FEF2F2',
				'alert-border-danger': '#FECACA',
				'alert-background-warning': '#FEFCE8',
				'alert-border-warning': '#FEF08A',
				'alert-background-green': '#F0FDF4',
				'alert-border-green': '#BBF7D0',
				'alert-background-info': '#F0F9FF',
				'alert-border-info': '#BAE6FD',
				// tab
				'tab-background': '#F9FAFB',
				'tab-border': '#E5E7EB',
				// tooltip
				'tooltip-background-light': '#FFFFFF',
				'tooltip-background-dark': '#111827',
				// toggle
				'toggle-off': '#E5E7EB',
				'toggle-on': '#DC4809',
				'toggle-dial-background': '#FFFFFF',
				'toggle-off-hover': '#D1D5DB',
				'toggle-off-border': '#D1D5DB',
				'toggle-on-hover': '#F18E63',
				'toggle-on-border': '#F8A581',
				'toggle-on-disabled': '#EEF2FF',
				'toggle-off-disabled': '#FFF3EE',
				// chart color
				'chart-purple-500': '#A855F7',
			},
			spacing: {
				'content-container': '43.5rem',
			},
			fontFamily: {
				sans: [ 'Figtree', 'sans-serif' ],
			},
			lineHeight: {
				7.5: '1.875rem', // 30px
				9.5: '2.375rem', // 38px
				11: '2.75rem', // 44px
			},
			borderWidth: {
				0.5: '0.5px',
				1.25: '1.25px',
			},
			width: {
				864: '864px',
				12: '12px',
			},
			boxShadow: {
				'sm-blur-1': '0 1px 1px rgba(0, 0, 0, 0.05)',
				'sm-blur-2': '0 1px 2px rgba(0, 0, 0, 0.05)',
			},
		},
	},
	variants: {
		extend: {
			borderWidth: [ 'last' ],
		},
	},
	corePlugins: {
		preflight: false,
	},
	important:
		':is(#srfm-dashboard-container, #srfm-settings-container, #srfm-page-header, #srfm-dialog-root, #srfm-add-new-form-container)',
} );
