
name: Playwright tests

on:
  pull_request:
    types: [ labeled ]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  Playwright:
    name: Test mandatory workflows
    if: ${{ github.event.label.name == 'e2e' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.15'

      - name: Install dependencies
        run: npm install --force

      - name: Generate build
        run: npm run build

      - name: Start Docker environment
        run: npm run play:up:gh

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=line

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop Docker environment
        run: npm run play:stop
        if: always()
