name: "PR Title Checker"
on:
  pull_request:
    branches:
      - master
      - next-release
      - dev
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:

      # Run the PR Title Checker action
      - name: PR Title Checker
        uses: thehanimo/pr-title-checker@v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/config/pr-title-checker.json"

          # Debug logging for PR Title Checker outputs
      - name: Debug PR Title Checker outputs
        run: |
          echo "PR Title Checker outputs: ${{ toJson(steps.pr_title.outputs) }}"

      - name: Perform Action if Title Check Passed
        if: success()
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
      # Add Jira link to PR description if title is valid
      # - name: Update PR description with Jira link
      #   uses: tzkhan/pr-update-action@v2
      #   if: success()
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     base-branch-regex: '[A-Za-z\d-_.\\/]+'
      #     head-branch-regex: '[A-Za-z\d-_.\\/]+'
      #     body-template: |
      #       Jira: https://brainstormforce.atlassian.net/browse/${{ steps.pr_title.outputs.issue_number }}
      #       ---
      #     body-update-action: 'prefix'
      #     body-uppercase-base-match: false
