
name: Update checklist for Release PR

on:
  pull_request:
    types: [ labeled ]

jobs:
  update_pr:
    name: Update checklist for Release PR
    if: ${{ github.event.label.name == 'Release PR' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.base_ref }} == master || ${{ github.base_ref }} == dev || ${{ github.base_ref }} == next-release ]]; then
              echo ::set-output name=match::true
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-branch.outputs.match == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '[A-Za-z\d-_.\\/]+'
          body-template: |
            ---
            ### Release Checklist:
            - [ ] Run to update version number  : `grunt version-bump --ver=<version-number>`
            - [ ] Verify `Stable tag` is `<version-number>` in readme.txt
            - [ ] Verify `Tested upto` is set to latest tested version of WordPress
            - [ ] Update version in `sureforms.php` in plugin description
            - [ ] Verify constant `SRFM_VER` in `sureforms.php` with latest version of SureForms
            - [ ] Generate README.md : `grunt readme`
            - [ ] Verify changelog `date` and `content` as per SureForms standards
            - [ ] Generate POT file : `npm run makepot`
            ---
          body-update-action: 'suffix'
          body-uppercase-base-match: false
